/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x59, 0x67, 0x22, 0x6A, 0x19, 0x87, 0x01, 0x17}


#define VIAL_UNLOCK_COMBO_ROWS { 1,1 }
#define VIAL_UNLOCK_COMBO_COLS { 0,11 }

#ifdef RGB_DI_PIN
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#endif
